# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f02f70ee1576983f56cde9b5463df92872a290d12021bda47b028da416367f2884641700b47527ecb0f6e4bb433e2657c44c3d86b8e77ac2dc322d6c7e09f882

test:
  secret_key_base: 78d39993d5ba4ce8e312bb58977cd93d7ff0fab1a70d210c8e85c1c57341e9c93264dd8588b10e957dea1a3a5703fc98eff925b52bbe703077d6fc12d69a3ad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
